### ISSUE TITLE
Version Error

### ISSUE THREAD

**Issue by Fouton** [FirenX/emu-coop#1]
in the version.lua, the patch numbers must be all numbers, since the util.lua uses a tonumber on them to compare them. This means that it's causing something to turn up nil and crash the lua immediately.

**Comment by FirenX** [comment]
Thanks for the report.
Is the whole script not working as a consequence? (Can't test it myself atm)

**Comment by FirenX** [comment]
Fixed. Changed versioning to numbers only.
