### ISSUE TITLE
Yes/No Radio Bubbles not controllable with left/right on keyboard

### ISSUE THREAD

**Issue by mysterypaint** [FirenX/emu-coop#6]
This is a bit of a small request, but can you allow left/right on the keyboard to move between yes/no options in the Lua script GUI? Alternatively, can we get tickboxes for those instead?

**Comment by FirenX** [comment]
Arrow keys not working during options selection is the fault of iuplua and I cannot fix it.
I can change the selections to checkboxes though.
I will definitely do that since the current Options GUI is confusing and checkboxes might help.

**Comment by FirenX** [comment]
Done in v1.14.
