### ISSUE TITLE
Regarding fairies and sharing death/health (LTTP Randomizer)

### ISSUE THREAD

**Issue by mysterypaint** [FirenX/emu-coop#8]
Playing with some friends, I noticed some inconsistencies whenever we died: Sometimes one fairy would be used, sometimes two would be used, and sometimes one player would use one while the other is sent to the game over screen... Is there any way to keep this consistent, or is it because we're sharing death while sharing health that's causing this issue? Should we just keep the Death option off?

**Comment by FirenX** [comment]
How many fairies total did you have in bottles?
From what I can tell it should work like this:

0 fairies: Both players die. No fairies after that.
1 fairy: The player actually dying gets revived and the partner has to save&quit or save&continue. No fairies now. Health is slightly desynced sinced fairy revival and s&c have different current health values. When one player gets/loses health it is synced again.
2+ fairies: Both get revived. Two less fairies total now.

Is that what happened?

**Comment by FirenX** [comment]
In v1.14 one fairy should revive both players unless the death of the partner got delayed. I wiill keep whatever behaviour it has in v1.14 for the time being.
